### ISSUE TITLE
Title of the plugin is not being translated to other languages

### ISSUE THREAD

**Issue by mikeallbutt** [DiscipleTools/disciple-tools-meetings#16]
![Screenshot 2024-04-23 at 5 20 42 PM](https://github.com/DiscipleTools/disciple-tools-meetings/assets/43966676/73c428f4-d5d2-4fe3-88b7-23a712693547)

The word 'Meetings' should be being translated into the language that the logged in user specifies.

**Comment by corsacca** [comment]
Thanks @mikeallbutt!
Fixed in v1.0.6
